# Generated by Django 5.2.6 on 2025-09-16 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="올바른 전화번호 형식이 아닙니다.", regex="^010\\d{8}$"
                    )
                ],
            ),
        ),
    ]
