# Generated by Django 5.2.6 on 2025-09-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "초급"),
                    ("intermediate", "중급"),
                    ("advanced", "고급"),
                    ("native", "원어민"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
