version: "3.8"

services:
  web:
    build: .
    env_file:
      - .env
    command: uvicorn language_exchange.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    # 포트 외부 노출 금지 (nginx만 80/443 노출)
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      # SSL 적용시 "443:443" 추가
    volumes:
      - static_volume:/static:ro
      - media_volume:/media:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    entrypoint: /bin/sh
    command: -c "sleep infinity"

volumes:
  static_volume:
  media_volume:
