# Generated by Django 5.2.6 on 2025-09-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_report_chatroomparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "일반 메시지"),
                    ("system_join", "시스템 메시지 - 입장"),
                    ("system_leave", "시스템 메시지 - 퇴장"),
                    ("system_info", "시스템 메시지 - 정보"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
