# Generated by Django 5.2.6 on 2025-09-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_message_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_system",
            field=models.BooleanField(default=False, verbose_name="시스템 메시지"),
        ),
    ]
