# Generated by Django 5.2.6 on 2025-09-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MatchingPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teaching_languages", models.JSONField(default=list)),
                ("learning_languages", models.JSONField(default=list)),
                ("interests", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "매칭 선호도",
                "verbose_name_plural": "매칭 선호도들",
                "db_table": "matching_preferences",
            },
        ),
        migrations.CreateModel(
            name="MatchingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender_preference",
                    models.CharField(
                        choices=[
                            ("male", "남성"),
                            ("female", "여성"),
                            ("any", "상관없음"),
                        ],
                        default="any",
                        max_length=10,
                    ),
                ),
                (
                    "university_preference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("seoul_area", "서울권"),
                            ("gyeonggi_area", "경기권"),
                            ("incheon_area", "인천권"),
                            ("busan_area", "부산권"),
                            ("daegu_area", "대구권"),
                            ("gwangju_area", "광주권"),
                            ("daejeon_area", "대전권"),
                            ("ulsan_area", "울산권"),
                            ("gangwon_area", "강원권"),
                            ("chungcheong_area", "충청권"),
                            ("jeolla_area", "전라권"),
                            ("gyeongsang_area", "경상권"),
                            ("jeju_area", "제주권"),
                            ("same_university", "같은 대학교"),
                            ("specific_university", "특정 대학교"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "specific_university",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("matched", "매칭됨"),
                            ("rejected", "거절됨"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "매칭 요청",
                "verbose_name_plural": "매칭 요청들",
                "db_table": "matching_requests",
            },
        ),
    ]
